# Generated by Django 4.2.4 on 2023-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='users/image')),
            ],
        ),
    ]
