# Generated by Django 4.2.4 on 2023-09-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='scrap_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
