# Generated by Django 4.2.4 on 2023-09-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_scrap_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='category',
        ),
    ]
